language: android
before_install: #1.1
- nvm install 6
- node --version
install: #1.2
- npm install
android: #1.3
  components:
  - build-tools-23.0.1
  - android-23
  - extra-android-m2repository
  - extra-google-google_play_services
  - extra-google-m2repository
  - addon-google_apis-google-16
script: 
  #- npm run ci #2 #run linter and tests
  - cd android && ./gradlew assembleRelease #3
before_deploy:
  - cp app/build/outputs/apk/app-release.apk app-release.apk
deploy:
  provider: testfairy
  api-key: $DEPLOY_API_KEY
  app-file: app-release.apk
  keystore-file: my-release-key.keystore
  storepass: $STOREKEY
  alias: govhack
  auto-update: true
